[tools]
go = "latest"
kubectl = "latest"
node = "lts"
rust = "latest"
gcloud = "latest"
gh = "latest"
terraform = "latest"
neovim = "latest"
lazygit = "latest"
delta = "latest"
direnv = "latest"
fzf = "latest"
zoxide = "latest"
herdr = "latest"
tree-sitter = "latest"
